services:

  # ==========================================
  # Go ShortenUrl Service & DB & Cache
  # ==========================================
  go-shorten-service:
    build:
      context: ./backend/shorten-api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:4000"
    env_file:
      - ./backend/shorten-api/.env

  # ==========================================
  # Web / Frontend
  # ==========================================
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - go-shorten-service
