upstream shorten_api {
    server go-shorten-service:4000;
    keepalive 1024;
}

upstream sso_api {
    server 100.89.19.104:8080;
    keepalive 128;
}

server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/auth {
        access_log off;
        proxy_pass http://sso_api/api/auth;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host 100.89.19.104:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/v1/shorten {
        access_log off;
        proxy_pass http://shorten_api/api/v1/shorten;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
